#!/bin/bash

if [ ! -f /var/restarts.txt ]; then
        echo 0 > /var/restarts.txt
fi

while true
do
    gdb -batch -ex "run" -ex "bt" -ex "info locals" -ex "info args" -ex "p this" --args /root/game/a.out ffa &>> /root/game/game.log
    old=`cat /var/restarts.txt`
    new=`expr $old + 1`
    echo $new > /var/restarts.txt
    sleep 1
done
